# Step 1: Modules caching
FROM golang:1.21.5-alpine as modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang:1.21.5-alpine as builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -tags migrate -o /bin/app ./cmd/user/http_server

# Step 3: Final
FROM alpine:3.19

EXPOSE 80

# GOPATH for scratch images is /
COPY --from=builder /app/config/user/* /config/user/
COPY --from=builder /bin/app /app
CMD ["/app"]