// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package postgresql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	Bio          string       `json:"bio"`
	PasswordHash string       `json:"password_hash"`
	Status       string       `json:"status"`
	CreatedDate  time.Time    `json:"created_date"`
	UpdatedDate  sql.NullTime `json:"updated_date"`
}
